### ISSUE TITLE
Evaluation on MPII

### ISSUE THREAD

**Issue by yaorong0921** [sandareka/FLEX#7]
Dear @sandareka ,

thank you for sharing your code and your nice work FLEX!
I have a question regarding experiments on MPII. In your paper, you mentioned that you "manually annotated 150 images with 600 object categories". Could you please share this as well? Otherwise, it is difficult to evaluate on the MPII dataset. 
Thank you in advance!

**Comment by sandareka** [comment]
Hi @yaorong0921 

Thank you for your interest in our paper. 

I added the object annotation file for MPII dataset. Please find it at:

https://github.com/sandareka/FLEX/blob/master/data/mpii/object_annotations.json

I will close the issue for now. If you have further issues please feel free to reopen.
